/**
 * AP Precalculus Unit 1 — 40 questions, 45 points total.
 * 35 × 1 pt + 5 multipart × 2 pt (Q36–Q40).
 * Exposed as window.UNIT1 for legacy script loading.
 */
;(function (global) {
  const UNIT1 = {
    id: 'ap-precal-unit-1',
    title: 'AP Precalculus — Unit 1 Assessment',
    subtitle: 'Polynomial, rational, and exponential function foundations',
    totalPoints: 45,
    questionCount: 40,
    instructions: [
      '40 questions · 45 points total · one question at a time.',
      'Use Check answer for feedback on the current item.',
      'Submit on question 40 when you are ready to score the full assessment.',
      'Multipart items (Q36–Q40): earn half credit when at least half of the parts are correct.',
    ],
    questions: [
      {
        id: 1,
        points: 1,
        topic: 'Rates of change',
        type: 'mc',
        prompt:
          'A quantity changes from 12 to 20 over an interval of length 4. What is the average rate of change?',
        choices: ['2', '3', '4', '8'],
        answer: 'A',
        feedbackCorrect: 'Average rate of change = (20 − 12) / 4 = 2.',
        feedbackWrong: 'Use (final − initial) / change in input.',
      },
      {
        id: 2,
        points: 1,
        topic: 'Polynomial end behavior',
        type: 'mc',
        prompt: 'For a polynomial with leading term −3x⁵, as x → ∞, f(x) →',
        choices: ['∞', '−∞', '0', '5'],
        answer: 'B',
        feedbackCorrect: 'Odd degree with negative leading coefficient → right end goes down.',
      },
      {
        id: 3,
        points: 1,
        topic: 'Zeros',
        type: 'numeric',
        prompt: 'If f(x) = (x − 2)(x + 5), what is the smaller zero of f?',
        answer: -5,
        tolerance: 0,
        answerDisplay: '−5',
      },
      {
        id: 4,
        points: 1,
        topic: 'Exponential growth',
        type: 'mc',
        prompt: 'Which function models exponential growth?',
        choices: ['f(x) = 3x + 2', 'f(x) = 2 · 3ˣ', 'f(x) = x³', 'f(x) = 3/x'],
        answer: 'B',
      },
      {
        id: 5,
        points: 1,
        topic: 'Degree',
        type: 'numeric',
        prompt: 'What is the degree of p(x) = 4x³ − x⁷ + 2?',
        answer: 7,
        tolerance: 0,
      },
      {
        id: 6,
        points: 1,
        topic: 'Average rate of change',
        type: 'numeric',
        prompt: 'For g(x) = x², find the average rate of change on [1, 3].',
        answer: 4,
        tolerance: 0.01,
        answerDisplay: '4',
      },
      {
        id: 7,
        points: 1,
        topic: 'Multiplicity',
        type: 'mc',
        prompt: 'At x = 2, f(x) = (x − 2)³(x + 1) crosses the x-axis because the multiplicity at 2 is',
        choices: ['odd', 'even', 'zero', 'negative'],
        answer: 'A',
      },
      {
        id: 8,
        points: 1,
        topic: 'Exponential evaluation',
        type: 'numeric',
        prompt: 'Evaluate 5 · 2³.',
        answer: 40,
        tolerance: 0,
      },
      {
        id: 9,
        points: 1,
        topic: 'End behavior',
        type: 'mc',
        prompt: 'A polynomial with even degree and positive leading coefficient has both ends',
        choices: ['going up', 'going down', 'crossing the x-axis', 'undefined'],
        answer: 'A',
      },
      {
        id: 10,
        points: 1,
        topic: 'Factoring',
        type: 'text',
        prompt: 'Factor completely: x² − 9. Enter the product form using parentheses (e.g. (x-3)(x+3)).',
        answer: '(x-3)(x+3)',
        feedbackWrong: 'Difference of squares: a² − b² = (a − b)(a + b).',
      },
      {
        id: 11,
        points: 1,
        topic: 'Rational zeros',
        type: 'mc',
        prompt: 'Which is a possible rational zero of 2x³ − 5x + 1 by the Rational Root Theorem?',
        choices: ['±1/2', '±2/5', '±5/2', '±1/3'],
        answer: 'A',
      },
      {
        id: 12,
        points: 1,
        topic: 'Exponential decay',
        type: 'mc',
        prompt: 'A car loses 12% of its value each year. The yearly multiplier is',
        choices: ['0.12', '1.12', '0.88', '1.88'],
        answer: 'C',
      },
      {
        id: 13,
        points: 1,
        topic: 'Remainder theorem',
        type: 'numeric',
        prompt: 'Use the Remainder Theorem: remainder when p(x) = x³ − 4x + 1 is divided by (x − 2).',
        answer: 1,
        tolerance: 0,
      },
      {
        id: 14,
        points: 1,
        topic: 'Complex zeros',
        type: 'mc',
        prompt: 'If 2 + i is a zero of a polynomial with real coefficients, which must also be a zero?',
        choices: ['2 − i', '−2 + i', 'i − 2', '2 + 2i'],
        answer: 'A',
      },
      {
        id: 15,
        points: 1,
        topic: 'Transformations',
        type: 'mc',
        prompt: 'Compared to y = x², the graph of y = (x − 3)² is shifted',
        choices: ['3 units right', '3 units left', '3 units up', '3 units down'],
        answer: 'A',
      },
      {
        id: 16,
        points: 1,
        topic: 'Polynomial division',
        type: 'numeric',
        prompt: 'Divide x² + 5x + 6 by (x + 2). What is the quotient (linear term coefficient)?',
        answer: 1,
        tolerance: 0,
        feedbackCorrect: 'Quotient is x + 3; leading coefficient is 1.',
        feedbackWrong: 'Synthetic or long division gives quotient x + 3.',
      },
      {
        id: 17,
        points: 1,
        topic: 'Exponential equation',
        type: 'numeric',
        prompt: 'Solve 3ˣ = 81 for x.',
        answer: 4,
        tolerance: 0,
      },
      {
        id: 18,
        points: 1,
        topic: 'Graph features',
        type: 'mc',
        prompt: 'The graph of an even-degree polynomial with a negative leading coefficient has',
        choices: [
          'both ends down',
          'both ends up',
          'left down, right up',
          'left up, right down',
        ],
        answer: 'A',
      },
      {
        id: 19,
        points: 1,
        topic: 'Average rate of change',
        type: 'numeric',
        prompt: 'h(t) = −16t² + 64t gives height in feet. Average velocity on [0, 2] seconds?',
        answer: 32,
        tolerance: 0.5,
        answerDisplay: '32 ft/s',
      },
      {
        id: 20,
        points: 1,
        topic: 'Zeros count',
        type: 'numeric',
        prompt: 'A degree-4 polynomial has at most how many real zeros?',
        answer: 4,
        tolerance: 0,
      },
      {
        id: 21,
        points: 1,
        topic: 'Exponential vs linear',
        type: 'mc',
        prompt: 'Over large x, which grows faster: f(x) = 2ˣ or g(x) = 100x?',
        choices: ['2ˣ', '100x', 'They grow equally', 'Depends on x only below 0'],
        answer: 'A',
      },
      {
        id: 22,
        points: 1,
        topic: 'Factoring',
        type: 'text',
        prompt: 'Factor: x² + 7x + 12. Enter as (x+a)(x+b) with smaller root first.',
        answer: '(x+3)(x+4)',
      },
      {
        id: 23,
        points: 1,
        topic: 'Multiplicity graph',
        type: 'mc',
        prompt: 'A zero of even multiplicity touches the axis but does not cross. True or false?',
        choices: ['True', 'False'],
        answer: 'A',
      },
      {
        id: 24,
        points: 1,
        topic: 'Composition',
        type: 'numeric',
        prompt: 'If f(x) = x + 2 and g(x) = x², find (f ∘ g)(3).',
        answer: 11,
        tolerance: 0,
      },
      {
        id: 25,
        points: 1,
        topic: 'Rational function',
        type: 'mc',
        prompt: 'For r(x) = 1/(x − 4), the vertical asymptote is',
        choices: ['x = 4', 'x = −4', 'y = 4', 'y = 0'],
        answer: 'A',
      },
      {
        id: 26,
        points: 1,
        topic: 'Polynomial construction',
        type: 'mc',
        prompt: 'A cubic with zeros −1, 0, and 2 could be',
        choices: ['x(x + 1)(x − 2)', '(x − 1)(x − 2)', 'x² − x − 2', 'x³ + 1'],
        answer: 'A',
      },
      {
        id: 27,
        points: 1,
        topic: 'Exponential parameters',
        type: 'numeric',
        prompt: 'In A(t) = 1200(0.95)ᵗ, what is the initial value?',
        answer: 1200,
        tolerance: 0,
      },
      {
        id: 28,
        points: 1,
        topic: 'Difference quotient',
        type: 'mc',
        prompt: 'The difference quotient for f at x with step h is',
        choices: [
          '(f(x+h) − f(x)) / h',
          'f(x+h) − f(x)',
          'f(x) / h',
          '(f(x) − f(h)) / x',
        ],
        answer: 'A',
      },
      {
        id: 29,
        points: 1,
        topic: 'Synthetic division',
        type: 'numeric',
        prompt: 'Synthetic division of x³ − 6x + 4 by (x − 2) gives remainder',
        answer: 0,
        tolerance: 0,
        feedbackCorrect: 'x = 2 is a zero.',
      },
      {
        id: 30,
        points: 1,
        topic: 'Logarithm intro',
        type: 'mc',
        prompt: 'log₂(8) equals',
        choices: ['2', '3', '4', '8'],
        answer: 'B',
      },
      {
        id: 31,
        points: 1,
        topic: 'Inverse relationship',
        type: 'numeric',
        prompt: 'If 2ˣ = 32, then x =',
        answer: 5,
        tolerance: 0,
      },
      {
        id: 32,
        points: 1,
        topic: 'Polynomial inequality',
        type: 'mc',
        prompt: 'For x² − 4 < 0, the solution interval is',
        choices: ['(−2, 2)', '(−∞, −2) ∪ (2, ∞)', '[−2, 2]', 'all real x'],
        answer: 'A',
      },
      {
        id: 33,
        points: 1,
        topic: 'Rate comparison',
        type: 'mc',
        prompt: 'Which has a constant rate of change?',
        choices: ['Linear', 'Quadratic', 'Cubic', 'Exponential'],
        answer: 'A',
      },
      {
        id: 34,
        points: 1,
        topic: 'Binomial expansion',
        type: 'numeric',
        prompt: 'In the expansion of (x + 1)⁴, the coefficient of x³ is',
        answer: 4,
        tolerance: 0,
      },
      {
        id: 35,
        points: 1,
        topic: 'Model selection',
        type: 'mc',
        prompt: 'Data rises quickly then levels off. Best model?',
        choices: [
          'Logistic or bounded exponential',
          'Linear',
          'Cubic with positive leading term',
          'Constant',
        ],
        answer: 'A',
      },
      {
        id: 36,
        points: 2,
        topic: 'Polynomial analysis',
        type: 'multipart',
        extension: true,
        prompt: 'Let p(x) = x³ − 4x.',
        parts: [
          {
            label: 'a',
            type: 'text',
            prompt: 'Factor p(x) completely over the reals.',
            answer: 'x(x-2)(x+2)',
            accept: ['x(x+2)(x-2)', 'x(x-2)(x+2)'],
            feedbackWrong: 'Factor out x first, then difference of squares.',
          },
          {
            label: 'b',
            type: 'numeric',
            prompt: 'How many distinct real zeros does p have?',
            answer: 3,
            tolerance: 0,
          },
        ],
        feedbackCorrect: 'Zeros at −2, 0, and 2.',
        feedbackPartial: 'Check both factoring and the zero count.',
      },
      {
        id: 37,
        points: 2,
        topic: 'Average rate of change',
        type: 'multipart',
        extension: true,
        prompt: 'For f(x) = x² − 3x on the interval [1, 4]:',
        parts: [
          {
            label: 'a',
            type: 'numeric',
            prompt: 'Compute the average rate of change.',
            answer: 2,
            tolerance: 0.01,
          },
          {
            label: 'b',
            type: 'mc',
            prompt: 'Is the function increasing on [1, 4]?',
            choices: ['Yes', 'No'],
            answer: 'A',
          },
        ],
      },
      {
        id: 38,
        points: 2,
        topic: 'Exponential model',
        type: 'multipart',
        extension: true,
        prompt: 'A bacteria culture doubles every 3 hours. Initially there are 500 bacteria.',
        parts: [
          {
            label: 'a',
            type: 'numeric',
            prompt: 'How many hours until the population first doubles?',
            answer: 3,
            tolerance: 0,
          },
          {
            label: 'b',
            type: 'numeric',
            prompt: 'How many bacteria after 6 hours?',
            answer: 2000,
            tolerance: 0,
          },
        ],
      },
      {
        id: 39,
        points: 2,
        topic: 'Complex zeros',
        type: 'multipart',
        extension: true,
        prompt: 'A quartic with real coefficients has zeros 1, −1, and 2i.',
        parts: [
          {
            label: 'a',
            type: 'mc',
            prompt: 'Which must be the fourth zero?',
            choices: ['−2i', '2', '−2', 'i'],
            answer: 'A',
          },
          {
            label: 'b',
            type: 'numeric',
            prompt: 'How many non-real zeros appear in the list (counting multiplicity)?',
            answer: 2,
            tolerance: 0,
          },
        ],
      },
      {
        id: 40,
        points: 2,
        topic: 'Synthesis',
        type: 'multipart',
        extension: true,
        prompt: 'Consider g(x) = (x − 1)²(x + 3).',
        parts: [
          {
            label: 'a',
            type: 'mc',
            prompt: 'At x = 1, the graph',
            choices: ['touches the axis', 'crosses the axis', 'has a hole', 'has a vertical asymptote'],
            answer: 'A',
          },
          {
            label: 'b',
            type: 'numeric',
            prompt: 'Sum of all real zeros (counting multiplicity).',
            answer: -1,
            tolerance: 0,
            answerDisplay: '−1',
            feedbackCorrect: 'Zeros: 1 (multiplicity 2) and −3 → 1 + 1 + (−3) = −1.',
            feedbackWrong: 'Zeros: 1 (twice) and −3. Sum = 1 + 1 + (−3) = −1.',
          },
        ],
      },
    ],
  }

  global.UNIT1 = UNIT1
  if (typeof module !== 'undefined') module.exports = UNIT1
})(typeof window !== 'undefined' ? window : globalThis)
